apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-component-child-skho
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-component-child-skho
    app.kubernetes.io/part-of: build-suite-component-update-gctu
  name: multi-component-child-skho
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multi-component-child-skho
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multi-component-child-skho
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-sfxb-tenant/build-suite-component-update-gctu/multi-component-child-skho@sha256:a317b8f328496edbeee67c9da37ae2e67592928b28b5e2785b72c459cbd2412c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
